GET http://localhost:5165/accounts

###
PUT http://localhost:5165/accounts/new
Content-Type: application/json

{
  "Name": "A conto4",
  "Company": "UBS",
  "OpenDate": "2022-01-01"
}

###
PUT http://localhost:5165/accounts/close
Content-Type: application/json

{
  "Id": "62b888daa670ce2ae2860829",
  "CloseDate": "2022-01-01T00:00:00"
}