GET http://localhost:5165/accounts
Authorization: Bearer {{$auth.token("julien")}}

###
PUT http://localhost:5165/accounts/new
Content-Type: application/json
Authorization: Bearer {{$auth.token("julien")}}

{
  "Name": "Conto A",
  "Company": "UBS",
  "OpenDate": "2022-01-01"
}

###
PUT http://localhost:5165/accounts/close
Content-Type: application/json
Authorization: Bearer {{$auth.token("julien")}}

{
  "Id": "631c42462559f9c5ba696a84",
  "CloseDate": "2022-01-02T00:00:00"
}

###
PUT http://localhost:5165/accounts/65d904e960691020cf2122b1/balances/new
Content-Type: application/json
Authorization: Bearer {{$auth.token("julien")}}

{
  "CheckDate": "2023-10-27T00:00:00",
  "AmountInChf": 12.95
}

###
GET http://localhost:5165/wealth
Authorization: Bearer {{$auth.token("julien")}}

###
GET http://localhost:5165/wealth?date=2021-06-01
Authorization: Bearer {{$auth.token("julien")}}

###
GET http://localhost:5165/accounts/64a573c6d14cd2d5915bee95/balances
Authorization: Bearer {{$auth.token("julien")}}
###
GET http://localhost:5165/trend
Authorization: Bearer {{$auth.token("julien")}}

###
GET http://localhost:5165/companies
Authorization: Bearer {{$auth.token("julien")}}

###
PUT http://localhost:5165/companies/UBS/investment/new
Authorization: Bearer {{$auth.token("julien")}}
Content-Type: application/json

{
  "InvestmentDate": "2023-10-27T00:00:00",
  "AmountInChf": 100.00
}
