GET http://localhost:5165/accounts
Authorization: Bearer {{token}}

###
PUT http://localhost:5165/accounts/new
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Name": "A conto 9",
  "Company": "UBS",
  "OpenDate": "2022-01-01"
}

###
PUT http://localhost:5165/accounts/close
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Id": "631c42462559f9c5ba696a84",
  "CloseDate": "2022-01-02T00:00:00"
}

###
PUT http://localhost:5165/accounts/648f43152c325d63225546a1/balances/new
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "CheckDate": "2022-10-27T00:00:00",
  "AmountInChf": 12.95
}

###
GET http://localhost:5165/wealth
Authorization: Bearer {{token}}

###
GET http://localhost:5165/wealth?date=2021-06-01
Authorization: Bearer {{token}}