GET http://localhost:5165/accounts

###
PUT http://localhost:5165/accounts/new
Content-Type: application/json

{
  "Name": "A conto3",
  "Company": "UBS",
  "OpenDate": "2022-01-01"
}

###
PUT http://localhost:5165/accounts/close
Content-Type: application/json

{
  "Id": "62a3a01c386ca9fb9cbc69b9",
  "CloseDate": "2022-01-01T00:00:00"
}